### ISSUE TITLE
Investigate setting horizontal axis on Weekly Reports to always use week (pref. Monday) increments

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-client#131]
Right now, the x-axis shows differing date increments depending on how large the range is. When it's set to a month (like the default), for example, it displays 2-day increments (which for weekly reports doesn't make sense since the number only changes Mondays):
<img width="1080" alt="screenshot 2018-12-06 12 19 41" src="https://user-images.githubusercontent.com/20972610/49600451-3b752400-f951-11e8-82fa-da65bea07dfd.png">
A couple of weeks means you get timestamps, which makes even less sense for weekly reports (where the time is set to midnight):
<img width="1084" alt="screenshot 2018-12-06 12 19 12" src="https://user-images.githubusercontent.com/20972610/49600542-70817680-f951-11e8-933f-41b6011c0570.png">

Hopefully there's a way to fix this without too much trouble.

**Comment by magsout** [comment]
the best way after talking with @karlcow and @laghee is to move our graphic line to a graphic bar
