### ISSUE TITLE
Add temporary needsdiagnosis view to test temp DB endpoint

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-client#145]
This will give me a chance to try out the new easy-add container @magsout created and let us see if the new database test route (https://github.com/webcompat/webcompat-metrics-server/pull/93) is configured correctly for the client side. 🎆

**Comment by laghee** [comment]
What's the best way to go about this, @magsout? 🤔 

Where do I add the temp `const NeedsDiagDbTest`? Do I need to create a new file or does it go into the `MetricsTemplate` index? And then I assume I need to import it into the layout index?

**Comment by magsout** [comment]
@laghee you want to add another item on the menu to test the new db ? or just test locally ?

**Comment by laghee** [comment]
@magsout Now that you mention it, testing locally would be sufficient. No sense in committing something we'll just roll back immediately.

**Comment by laghee** [comment]
@magsout Testing this locally shows that there's something wrong with my endpoint -- the client can't read the data. I think this is because I'm sending a string date and an integer count, whereas the original endpoints use strings for both the date stamp and the count.

Going through the metrics-client code, I'm having trouble finding where I can make a change (or changes) to expect an integer count (so I can make sure I'm right about the problem). I assumed it was somewhere in the `normalize` or `get` functions, but I'm not seeing an obvious string-handling segment... Can you point me to the right spot? 😁

**Comment by magsout** [comment]
@laghee would you give me the endpoint to understand the error? if you do not mind ;)

**Comment by laghee** [comment]
@magsout Sure! So the original is `https://webcompat-metrics.herokuapp.com/data/needsdiagnosis-timeline` and the database test that's now live is `https://webcompat-metrics.herokuapp.com/data/needsdiagnosis-dbtest`. 

Hmm. Now that I just wrote that, it occurs to me that it might possibly be another problem.... The database is being queried for the specific date range rather than automatically returning all the data each time and slicing out the non-relevant parts as before. Without the params (like, `?from=2019-02-26&to=2019-03-11` or whatever), an empty response is returned. The client has a default range, though, right? So maybe that's not a problem? 🤷‍♀️

**Comment by karlcow** [comment]
@laghee a GET on https://webcompat-metrics.herokuapp.com/data/needsdiagnosis-dbtest it fails with a 400, because it doesn't provide a default range. It means the client in the current condition is REQUIRED to send arguments. Maybe we should send something by default.

https://github.com/webcompat/webcompat-metrics-server/blob/ccbd39399ab0c0b83cd4625c9bd5b152cdfef703/ochazuke/__init__.py#L106-L107

apart of this, this is working I guess

```
http GET 'https://webcompat-metrics.herokuapp.com/data/needsdiagnosis-dbtest?from=2019-03-11&to=2019-03-11' 'Accept:application/json'
```

```http
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 1272
Content-Type: application/json
Date: Thu, 14 Mar 2019 02:18:55 GMT
Server: gunicorn/19.8.1
Vary: Origin
Via: 1.1 vegur

[
    {
        "count": 123, 
        "timestamp": "2019-03-11T00:11:05Z"
    }, 
    {
        "count": 122, 
        "timestamp": "2019-03-11T01:10:55Z"
    }, 
    {
        "count": 120, 
        "timestamp": "2019-03-11T02:10:34Z"
    }, 
    {
        "count": 120, 
        "timestamp": "2019-03-11T03:10:16Z"
    }, 
    {
        "count": 119, 
        "timestamp": "2019-03-11T04:10:24Z"
    }, 
    {
        "count": 118, 
        "timestamp": "2019-03-11T05:11:02Z"
    }, 
    {
        "count": 117, 
        "timestamp": "2019-03-11T06:10:12Z"
    }, 
    {
        "count": 117, 
        "timestamp": "2019-03-11T07:11:14Z"
    }, 
    {
        "count": 117, 
        "timestamp": "2019-03-11T08:10:27Z"
    }, 
    {
        "count": 119, 
        "timestamp": "2019-03-11T09:10:48Z"
    }, 
    {
        "count": 120, 
        "timestamp": "2019-03-11T10:10:44Z"
    }, 
    {
        "count": 120, 
        "timestamp": "2019-03-11T11:10:33Z"
    }, 
    {
        "count": 121, 
        "timestamp": "2019-03-11T12:10:23Z"
    }, 
    {
        "count": 121, 
        "timestamp": "2019-03-11T13:10:16Z"
    }, 
    {
        "count": 121, 
        "timestamp": "2019-03-11T14:10:57Z"
    }, 
    {
        "count": 121, 
        "timestamp": "2019-03-11T15:11:07Z"
    }, 
    {
        "count": 121, 
        "timestamp": "2019-03-11T16:10:50Z"
    }, 
    {
        "count": 121, 
        "timestamp": "2019-03-11T17:10:26Z"
    }, 
    {
        "count": 121, 
        "timestamp": "2019-03-11T18:10:33Z"
    }, 
    {
        "count": 123, 
        "timestamp": "2019-03-11T19:10:40Z"
    }, 
    {
        "count": 123, 
        "timestamp": "2019-03-11T20:10:16Z"
    }, 
    {
        "count": 123, 
        "timestamp": "2019-03-11T21:10:53Z"
    }, 
    {
        "count": 123, 
        "timestamp": "2019-03-11T22:10:10Z"
    }, 
    {
        "count": 123, 
        "timestamp": "2019-03-11T23:10:22Z"
    }
]

```

**Comment by karlcow** [comment]
AH! no WAIT! my bad. :) You are missing the header of the JSON. 

```
{
  "about": "Hourly NeedsDiagnosis issues count",
  "date_format": "w3c",
  "timeline": [
```

**Comment by magsout** [comment]
@laghee oups, missed the ping.

Yep @karlcow is right. you missed the key `timeline`. Another thing the format sending is different. The response of  `needsdiagnosis-timeline` is an object:

```
{
  timeline:[{}, {}, {ø]
}
```

The response of  `eedsdiagnosis-dbtest` is an array:
```
[{}, {}, {}]
```

**Comment by laghee** [comment]
> @laghee a GET on https://webcompat-metrics.herokuapp.com/data/needsdiagnosis-dbtest it fails with a 400, because it doesn't provide a default range. It means the client in the current condition is REQUIRED to send arguments. Maybe we should send something by default.
>
I decided to return a 400 on missing params because the client is already configured to send a default range of the last 30 days. Do you think I should add a default response for no params, @karlcow @magsout?

BTW -- thanks for the fixes on my json formatting -- now working with the client side!

**Comment by magsout** [comment]
@laghee 

>Do you think I should add a default response for no params, @karlcow @magsout?

yes, I already render error message when it occurs. This helps to understand the error

```js
handleErrorSubmit(payload) {
    this.setState({
      isFetching: false,
      error: {
        message: ObjectNested.get(payload, "message", "Error"),
        errors: ObjectNested.get(payload, "errors", []),
        code: ObjectNested.get(payload, "code"),
      },
    });
  }
```
