### ISSUE TITLE
Add a min-date for "from" in filter range

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-client#154]
@laghee maybe, i can think how I can add a min-date on the from input? What do you think? (let open a new issue if needed)

_Originally posted by @magsout in https://github.com/webcompat/webcompat-metrics-client/pull/148#issuecomment-477944482_

**Comment by magsout** [comment]
@laghee min-date 28/03 ?

**Comment by laghee** [comment]
Yes -- all three of the new ones (`needstriage`, `needscontact`, and `sitewait`) started collecting yesterday.

**Comment by laghee** [comment]
@magsout This is a note to remind myself later to update this when/if I figure out how to add in older data points.
