### ISSUE TITLE
put min-max out of the graph

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-client#163]
Currently the min-max values of the graph are on top of the graph, which in some days cover some of the data, depending on how the graph is trending. 
We should probably put the min-max box, outside of the graph area. 

<img width="305" alt="Capture d’écran 2019-04-09 à 08 11 58" src="https://user-images.githubusercontent.com/505230/55762840-7b831980-5a9f-11e9-9dba-ba90718bd09d.png">

**Comment by magsout** [comment]
@karlcow 👍

**Comment by magsout** [comment]
oups again:
![Capture d’écran 2019-05-01 à 21 52 47](https://user-images.githubusercontent.com/1997108/57038935-7d359c80-6c5b-11e9-9d35-21eabe58490d.png)
