### ISSUE TITLE
Add a current value in the min-max box.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-client#164]
The min-max box is cool because it shows us the min-max of the range we are looking at. 
But maybe we could also display the now value.

**Comment by magsout** [comment]
```
Min: 363 (2019-04-01)
Max: 488 (2019-02-04) 
Current: 123 (2019-09-94)
```

@karlcow `current` is a good label? Or now?

**Comment by karlcow** [comment]
current is perfect
