### ISSUE TITLE
Move webcompat dashboard 

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat-metrics-client#172]
After an email to @miketaylr and a talked with @karlcow on irc. 

It's possible to called an endpoint on webcompat to keep back the data.

Here the fonction on webcompat : https://github.com/webcompat/webcompat.com/blob/cc35b31a6246d91c39c46522448614916da64e93/webcompat/views.py#L514-L525 and the endpoint https://webcompat.com/api/issues/category/needstriage?per_page=100

What we need to do:
- handle pagination on JavaScript side
- handle filters on JavaScript side https://webcompat.com/dashboard/triage
![Capture d’écran 2019-05-01 à 10 25 02](https://user-images.githubusercontent.com/1997108/57010135-65c6c700-6bfb-11e9-981d-e4747eed041e.png)
- add a reducer to mimik this function https://github.com/webcompat/webcompat.com/blob/cc35b31a6246d91c39c46522448614916da64e93/webcompat/dashboard.py#L17-L47

@miketaylr 
- what do you think? 
- is it revelant to work on it and moving the dashborad?
- is CORS are allowed on webcompat.com ?
- do you at first add back completly the same thing on webcompat?

**Comment by miketaylr** [comment]
Note: I wonder if the dashboard is considering pagination, the current dashboard shows 100 total bugs. But I see 500 untriaged issues: https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3Aneedstriage%20 😓 😅 😰 

I think this is useful, but I want to get input from @cipriansv, @softvision-sergiulogigan and @softvision-oana-arbuzov if this is something they use or will use.

**Comment by magsout** [comment]
@miketaylr yes for now GH is limited page by 100 items. So we thought we can add the logic on client side to handle it.

**Comment by softvision-oana-arbuzov** [comment]
@miketaylr , it is useful to know the correct number of issues that are older than 48hours, in order to estimate the time we spend to lower the number of issues (Hard core triaging or not) . 

Also we consider it would be better to merge the dashboard https://webcompat.com/dashboard/triage with the main one https://webcompat-dashboard.herokuapp.com/ , by creating a new section with 48hours/needsinfo issue graphic.  

Something like:
![image](https://user-images.githubusercontent.com/12184325/57456862-11fd5300-7277-11e9-973c-5114b2e9d506.png)

It is better to have all dashboards in one place.

**Comment by miketaylr** [comment]
Thanks for the feedback @softvision-oana-arbuzov, very helpful!

**Comment by magsout** [comment]
@miketaylr how I can name this new section ?

**Comment by miketaylr** [comment]
Maybe something simple "Untriaged Issues > 48Hours" or "Untriaged older than 48h". Or something like that.

**Comment by magsout** [comment]
@miketaylr @softvision-oana-arbuzov I left all the select. is it useful or not?

![Screenshot_2019-05-11 webcompat-metrics-client](https://user-images.githubusercontent.com/1997108/57566624-792e1b00-73cf-11e9-99d5-fa2ed067fdcb.png)

**Comment by softvision-oana-arbuzov** [comment]
@magsout , looks nice, the select is useful and we could go with the "Untriaged older than 48h" section title.

**Comment by miketaylr** [comment]
Awesome, thanks!

**Comment by karlcow** [comment]
Is this fixed?

**Comment by magsout** [comment]
@karlcow not yet. I’m finishing the new dashboard
