### ISSUE TITLE
"Current" label in min-max box shows no data when range doesn't cover today

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-client#197]
I noticed this particularly with weekly reports, but it happens any time a date range is chosen that doesn't include the current day. I wonder if we should either include a "current" value only when the range includes today's date? In the case of weekly reports, maybe we could change it to "latest" and give the last recorded week's total? Not sure how complicated either of those options would be...

**Comment by laghee** [comment]
![Screenshot 2019-08-05 18 18 01](https://user-images.githubusercontent.com/20972610/62480135-55505a80-b7af-11e9-9ae3-7635f665a116.png)

**Comment by magsout** [comment]
@laghee no longer current https://webcompat-dashboard.herokuapp.com/weeklyreports?from=2019-09-29&to=2019-12-01

**Comment by laghee** [comment]
Thanks, you're right -- looks like this was fixed in #194! ❤️ 🎉
