### ISSUE TITLE
Add TSCI iframe chart (temp)

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat-metrics-client#212]
This is probably going to be ugly at first, but I'll give it a whirl...

**Comment by laghee** [comment]
Oh, YEAH. Super-duper ugly! 😝 

So, two issues here, one of which might have been avoided by not ignoring all the React bits:

**One** --> it takes some time for the `iframe` content to load... (I'm using a test copy of the old TSCI chart page for now.)
![Screenshot 2019-11-23 15 09 12](https://user-images.githubusercontent.com/20972610/69479973-59a29100-0dfb-11ea-9c1b-88b86b31a2c5.png)

**Two** --> I need to figure out a way to use more of the existing structure so this doesn't look so terrible/you can actually see something once it does load)...
![Screenshot 2019-11-23 15 09 34](https://user-images.githubusercontent.com/20972610/69480000-9a020f00-0dfb-11ea-99d5-2ade6160fb86.png)

**Comment by laghee** [comment]
If you happen to have a few minutes at some point, @magsout, I'm trying to figure out the best way to use the MetricsTemplate to render an `iframe`... (desole 😜 )

https://github.com/webcompat/webcompat-metrics-client/blob/6f19f35e4176ec0976100bed051a071ae2cfce21/src/containers/WeeklyReports/index.js#L36
Can I skip the renderChart part above and just stick the `iframe` in below?? (Right now I'm not dealing with fetching data, but eventually I'll need to grab the spreadsheet ID from an endpoint and use that to construct the `iframe` link.)

**Comment by laghee** [comment]
OK, that's a little better:
![Screenshot 2019-11-23 16 08 56](https://user-images.githubusercontent.com/20972610/69480867-9fffec00-0e0b-11ea-8024-7529ef7400b5.png)

Not responsive, but at least readable!

**Comment by magsout** [comment]
@laghee I will (on y todo list)

**Comment by magsout** [comment]
@laghee I can work on it if you want. See what changed I have to do.

We need to create a Small component for the iframe reponsive mode ;)

**Comment by laghee** [comment]
@magsout It might be possible to fix it temporarily by just changing some stuff in my terrible CSS:
```
    <iframe
      style={{
        position: "relative",
        overflow: "auto",
        height: 600,
        maxHeight: "100%",
        width: "100%",
        maxWidth: "100%",
        sandbox: "",
      }}
      src={spreadsheetBaseUrl + spreadsheetID + spreadsheetEnd}
    />
```
In theory, the `iframe` is going to be temporary, so I wouldn't want you to have to do a bunch of work just to have to change it back later... 🤔, but let me know what you think!

**Comment by magsout** [comment]
@laghee I’ll take a look tomorrow

**Comment by magsout** [comment]
@laghee I code something here https://github.com/webcompat/webcompat-metrics-client/compare/issues/212...proposal/issues/212?expand=1 what do you think ?
