### ISSUE TITLE
Add view for viewing Firefox Interventions data

### ISSUE THREAD

**Issue by denschub** [webcompat/webcompat-metrics-client#293]
**This depends on a PR inside the metrics-server: https://github.com/webcompat/webcompat-metrics-server/pull/135**

I started working on this, but then got confused a bit by the structure, which I would need some time to get into. Luckily, @magsout pinged me and asked if he can/could/should implement the frontend for the PR, and since I am absolutely not opposed, here is a description of what I imagined.

* A new view that shows numbers for our WebCompat interventions. I suggest "Firefox WebCompat interventions" as title and "Tracking available and deployed WebCompat interventions in Firefox products" as subtitle, so it's absolutely clear this is a Firefox-only thing.
* The endpoint in the metrics server will be `/data/firefox-interventions`, and available parameters are explained in the [server PR](https://github.com/webcompat/webcompat-metrics-server/pull/135).
* We need four filters for the data to make sense:
  * `start`: A timestamp `YYYY-MM-DD` for the data's start time. This is pretty much the existing `from` but with a different name (sorry). A good default here is probably a year ago, or the start of the current year, since the resolution is pretty low (one datapoint per day)
  * `end`: Same timestamp, like the existing `to` parameter. Probably the current day as a default.
  * `distribution`: A `select` field to allow the user to select between the Interventions distribution, with the following values:
    * `upstream`: the default
    * `android-components`
    * `mozilla-central`
    * `mozilla-beta`
    * `mozilla-release`
  * `type`: A `select` field to allow filtering the intervention types:
    * `all`: default, can be labeled with "All Interventions"
    * `injection`: can be labeled with "CSS/JS injections"
    * `ua_override`: labeled as `UA override` or `User-Agent override` if there is enough space.
* The API endpoint will always return a JSON, which is always an identical looking array of objects with the following form:
  ```json
  [
    {
      "datetime": "2020-01-01T00:00:39.937Z",
      "counters": {
        "all": 4,
        "android": 30,
        "desktop": 16
      }
    }
  ]
  ```
  * `datetime`: An ISO 8601 date. We can cut this down to the day only, as there *should not* be any duplicates
  * `counters`: Contains the counters to show as lines
    * `all`: This is actually not a sum of other fields, but these are interventions that are universal to all platforms. Can we change that to `universal` if we have a legend?
    * `android`: Number of interventions affecting android
    * `desktop`: Number of interventions affecting desktop
* Because we have three different counters, the ideal way to show this would be as a stacked line chart. If we can't do a stacked line chart, we can reduce the counters with `all+android+desktop` to a single value to show as a simple line chart.

I hope I explained everything well. Please let me know if there are additional questions! :)

**Comment by denschub** [comment]
As an additional note: For testing, it's possible to use the PR deployment at https://webcompat-metrics-pr-135.herokuapp.com/data/firefox-interventions?distribution=upstream&type=all&start=2020-01-01&end=2020-12-31, until the server PR is merged and deployed!

**Comment by magsout** [comment]
@denschub about start and end, when did you start to record data?

**Comment by magsout** [comment]
WIP:

![Screenshot_2020-06-09 webcompat metrics client - Firefox WebCompat interventions dashboard](https://user-images.githubusercontent.com/1997108/84147581-efcb9b00-aa5d-11ea-91b8-0860a05524e6.png)


<img width="1438" alt="Screen Shot 2020-06-09 at 14 32 25" src="https://user-images.githubusercontent.com/1997108/84147675-1984c200-aa5e-11ea-9e9c-889d8465a61c.png">
<img width="1430" alt="Screen Shot 2020-06-09 at 14 32 10" src="https://user-images.githubusercontent.com/1997108/84147679-1ab5ef00-aa5e-11ea-80f9-93cdcc1b8996.png">

**Comment by denschub** [comment]
@magsout I started recording 2019-12-03, but there have been a couple of times where the data didn't update because Heroku shut me down. But there are no datasets before 2019-12-03.

You're WIP already looks super awesome, and I'll leave comments on the PR.

**Comment by magsout** [comment]
done 👍
