### ISSUE TITLE
[proposal] change repo name to webcompat-metrics-client

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-metrics-client#36]
I'd like to do the following:

1. rename this repo to webcompat-metrics-client
2. create a new repo webcompat-metrics-server to power the API for the client
3. replace the existing dummy data with the metrics-server output (https://github.com/webcompat/webcompat-metrics/commit/1b303380e9b65ea93d72c171a1e1385e64c5163a)

I'd like @karlcow to build the webcompat-metrics-server to serve the initial needsdiagnosis data (and whatever we need to serve in the future)

Thoughts @karlcow @magsout?

**Comment by karlcow** [comment]
Having a separate repo will help decouple the client and the server.
It will make it less likely to have a very high dependency in between the data set and the way we show them to the world.

It also allows  the possibility for other clients/consumers.

* `webcompat-metrics-client`
* a CLI client for people who would like to access data into their terminal or their own UI
* webcompat.com can benefit of it too by having ways to pull the data into any UI where it would be useful.

Some of our data are dynamics (latest needsdiagnosis total number) but some are static history of the needsdiagnosis total number. 

In addition, the server has two components:

1. Expose the data through an HTTP API
2. Collect through cron scripts (probably?) some of the data into the backend for the static data.

It also makes it easier for @magsout to focus on the client without being pulled into the API development. There will be probably initial coordination on how to consume the data and which type of documentation/navigated inserted in the HTTP API responses or out-of-band with hard-coded URLs and versioning.

**Comment by magsout** [comment]
I agree with both of you. I have talked with you (email + irc) and I think it's a good thing.

**Comment by magsout** [comment]
@miketaylr what next? 

- rename this repo to webcompat-metrics-client
- remove all node files on this repo?
- made this repo only for the client?

**Comment by karlcow** [comment]
@miketaylr @magsout Created https://github.com/webcompat/webcompat-metrics-server

* Keep the current fake server in webcompat-metrics-client (if it helps you develop the client) Just the time that there is an instance up in the air for webcompat-metrics-server

**Comment by miketaylr** [comment]
> rename this repo to webcompat-metrics-client

Yeah, we can do this now. I think let's wait for @karlcow to have something functional that serves the data you need before moving forward with removing anything else server related.

**Comment by karlcow** [comment]
You can change the name. :)

**Comment by magsout** [comment]
I let @miketaylr doing it

**Comment by miketaylr** [comment]
So, we can close here? Maybe open an issue to remove the mock data once @karlcow's server is up and running?

**Comment by magsout** [comment]
I’m going to open a PR because I added this endpoint https://github.com/webcompat/webcompat-metrics-server/issues/7 in the dev serv of the client

**Comment by magsout** [comment]
@miketaylr when do you think is appropriate to remove the codebase of the server, clean and update documentation? Waiting the server is running at some point, or the temporary endpoint is enought?
