### ISSUE TITLE
avoid displaying numbers when at large scales.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-client#369]
On the weekly issue report, when the graph is displayed at a large scale, the numbers are covering each others and make the graph unreadable.
http://webcompat-dashboard.herokuapp.com/weeklyreports?from=2013-09-01&to=2021-04-04

We should find a way to not display the numbers as soon as they start to go over each others.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/505230/113522572-962ff080-95dc-11eb-9f07-ccf7f4e4564b.png">

**Comment by magsout** [comment]
@karlcow maybe one year? Or two? I could limit the datepicker between us.

**Comment by karlcow** [comment]
So I made an example for what I meant.
https://www.la-grange.net/2021/04/06/chart/weekly.html
