### ISSUE TITLE
Create dashboard to track needsdiagnosis burndown

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-metrics-client#4]
Some good conversation in #2, but this issue scopes it to just needsdiagnosis.

@karlcow has a script at https://gist.github.com/karlcow/92347ffc71e5b59ba21cb3e061a76e59 which is cool.

@karlcow, can you send me the content of the needsdiagnosis.txt so i can bootstrap historical data into a db? i'll work on something that updates daily.

**Comment by miketaylr** [comment]
OK! @magsout is gonna help me scaffold out the frontend for this, and I'll build the backend/database component. I'll file some bugs to track that.

**Comment by miketaylr** [comment]
Tracking this here: https://github.com/webcompat/webcompat-metrics/projects/2

**Comment by karlcow** [comment]
@miketaylr 

> can you send me the content of the needsdiagnosis.txt so i can bootstrap historical data into a db? i'll work on something that updates daily.

Yup I have been updating the comment in #2 every 2 days. I just updated the last week. 
Check https://github.com/webcompat/webcompat-metrics/issues/2#issuecomment-365105311

**Comment by miketaylr** [comment]
Thanks @karlcow!

**Comment by karlcow** [comment]
@magsout In https://github.com/webcompat/webcompat-metrics-server/issues/7
I'm exposing the data.
It follows the format we agreed on in https://github.com/webcompat/webcompat-metrics-server/issues/3#issuecomment-382632526

You can grab them at
http://www.la-grange.net/tmp/needsdiagnosis-timeline

This is just a static file for now. I will make it updated every hour very soon.
Design your client in a way where `domain_name`, `path` are variables. So we can change anytime these two parameters in hopefully a near future once we figured out https://github.com/webcompat/webcompat-metrics-server/issues/1

**Comment by karlcow** [comment]
`→ http HEAD http://www.la-grange.net/tmp/needsdiagnosis-timeline`

```http
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Length: 6410
Content-Location: needsdiagnosis-timeline.json
Content-Type: application/json
Date: Thu, 26 Apr 2018 04:49:29 GMT
ETag: "190a-56ab918f8b600;56ab90b062780"
Expires: Thu, 03 May 2018 04:49:29 GMT
Keep-Alive: timeout=5, max=100
Last-Modified: Thu, 26 Apr 2018 04:48:24 GMT
Server: Apache/2.4.29 (FreeBSD)
TCN: choice
Vary: negotiate
```

Ah yes. Significant details (I can change some of them to your convenience)

* `Content-Type: application/json` I don't remember maybe I should do `text/json`
* `ETag: "190a-56ab918f8b600;56ab90b062780"` This will change with each new release so it's a good way to poll if the data have changed (cache, etc.)
* `Expires: Thu, 03 May 2018 04:49:29 GMT` for caching I could probably set it to expire in one hour time, once the next batch is ready. 

Tell me if you need more things for the format or the HTTP headers.

**Comment by magsout** [comment]
DONE ;)
