### ISSUE TITLE
adding code of conduct

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat-metrics-client#45]
I would like to add a code of conduct on the project as on webcompat https://github.com/webcompat/webcompat.com/blob/master/CODE_OF_CONDUCT.md

can I added exactly same content? I need to ask someone the permission?

Who should I add in the contat @karlcow @miketaylr ?

**Comment by miketaylr** [comment]
> Who should I add in the contat @karlcow @miketaylr ?

You could add any of us 3 working on this, no issue from me.

+1 for COC, you can steal the content, that document itself originated from another one (with some minor lang edits, I believe): https://github.com/webcompat/webcompat.com/blob/master/CODE_OF_CONDUCT.md#attribution

**Comment by karlcow** [comment]
no issue. Ride on.
