### ISSUE TITLE
Scaffold out frontend for needsdiagnosis dashboard

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-metrics-client#5]
Everything we would need to serve an app that will consume a JSON api, and display a sweet chart. ✨

**Comment by miketaylr** [comment]
OK @magsout, if you clone the repo and run `npm start`, you'll have the following route for the dashboard to live:

http://localhost:3000/needsdiagnosis

I'll start building out the real API in #9 next.

**Comment by magsout** [comment]
Components:
- [ ] Header
- [ ] Footer
- [ ] UIComponent

Containers: 
- [ ] Header
- [ ] Footer
- Needsdiagnosis dashboard

**Comment by magsout** [comment]
DONE ;)
