### ISSUE TITLE
Figure out hosting for dashboards

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-metrics-client#6]
I think we can get Mozilla to hook us up with heroku hosting.

**Comment by magsout** [comment]
https://github.com/webcompat/webcompat-metrics-server/issues/23

**Comment by magsout** [comment]
For now we use gh_pages and fetch data from heroku, @miketaylr, maybe using a subdomain from webcompat or anything could be cool?

**Comment by miketaylr** [comment]
> For now we use gh_pages and fetch data from heroku, @miketaylr, maybe using a subdomain from webcompat or anything could be cool?

Sounds good! I think for now, just a gh-pages domain is great and we'll figure out something fancier a little down the road.

**Comment by magsout** [comment]
done
