### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-metrics-client#64]

**Comment by miketaylr** [comment]
<img width="275" alt="screen shot 2018-06-19 at 3 47 29 pm" src="https://user-images.githubusercontent.com/67283/41623353-1563a434-73d8-11e8-86db-02b3dd4558f6.png">

**Comment by miketaylr** [comment]
@magsout, @laghee is interested in working on this!

**Comment by magsout** [comment]
@miketaylr coool, thanks @laghee ping me if you have any question or need help.

**Comment by magsout** [comment]
You can use https://github.com/jantimon/html-webpack-plugin with `favicon` option 
![capture d ecran 2018-06-22 a 11 19 17](https://user-images.githubusercontent.com/1997108/41768987-1f2431d6-760e-11e8-9128-926d0c19901c.png)

**Comment by laghee** [comment]
Hey, @magsout -- do you think it makes sense to just port over the ready-made webcompat favicon files to pass to `html-webpack-plugin`? Is there any reason to use something like [favicons-webpack-plugin](https://github.com/jantimon/favicons-webpack-plugin) to generate all the variations again?

**Comment by magsout** [comment]
@laghee I like the idea to use `favicons-webpack-plugin`. We host only one PNG and generate in production all the assets.

**Comment by laghee** [comment]
@magsout Yep, `favicons-webpack-plugin` seems to work well! The only issue I see is that using the 196x196 webcompat png (which I used to get started), it doesn't seem to render as well as the original. I'm no graphics guru, but I assume there's some way to get a better png by using the svg in `/logo`? Should I use any online converter or is there a better way?
