### ISSUE TITLE
Make the default range +1 day

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-client#74]
Not sure if it's a question of TZ. :)
but in Japan at least, if I enter https://webcompat.github.io/webcompat-metrics-client/

I get https://webcompat.github.io/webcompat-metrics-client/?from=2018-05-25&to=2018-06-25

right now it is 12:29 JST

<img width="1074" alt="capture d ecran 2018-06-25 a 12 30 09" src="https://user-images.githubusercontent.com/505230/41829060-9177cca4-7873-11e8-9a0d-84c02fa45c0e.png">

it seems to show the data until June 24 at 24:00 
 
if I change the date to be tomorrow aka https://webcompat.github.io/webcompat-metrics-client/?from=2018-05-25&to=2018-06-26

I get the data from 25 00:00 JST to 25 12:29 JST

<img width="1065" alt="capture d ecran 2018-06-25 a 12 33 08" src="https://user-images.githubusercontent.com/505230/41829127-fc82e934-7873-11e8-803a-63691b4266cc.png">

or zooming in a bit.

"Default"
<img width="675" alt="capture d ecran 2018-06-25 a 12 35 27" src="https://user-images.githubusercontent.com/505230/41829214-69ce150e-7874-11e8-8785-1cf855b5c075.png">

Now
<img width="679" alt="capture d ecran 2018-06-25 a 12 35 46" src="https://user-images.githubusercontent.com/505230/41829238-8ba3fa4a-7874-11e8-96e0-4fcf0e4b9450.png">

**Comment by magsout** [comment]
I guess is something about UTC https://github.com/iamkun/dayjs/pull/168

**Comment by prantlf** [comment]
@karlcow , you want to use only the date part of the `dayjs` object, but you initialise it with the full date + time. The time part in the local time zone causes the occasional shift of the day. I [commented](https://github.com/iamkun/dayjs/issues/249#issuecomment-418607202) about it at #249.

Having a date-only mode in Day.js, or an UTC mode as a workaround will make the usage easier. Until then, you need to be aware and deal with the full date + time value, as you would, if you used the plain JavaScript `date`.

**Comment by magsout** [comment]
fixed https://github.com/webcompat/webcompat-metrics-server/issues/39
