### ISSUE TITLE
Do not resize the range of data

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-client#75]
When requesting for a range which has a wider range than the available data, do not change the min-max values to fit the data range.

For example in this graph I have selected until June 28.
<img width="772" alt="capture d ecran 2018-06-25 a 15 06 58" src="https://user-images.githubusercontent.com/505230/41833057-be68025e-7889-11e8-92e7-46e6df6b2e86.png">

The data are available until June 25 and the graph is resized to fit this range instead of showing the white space on the right.

**Comment by magsout** [comment]
fixed by https://github.com/webcompat/webcompat-metrics-client/pull/96
