### ISSUE TITLE
horizontal axis should be time regular

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat-metrics-client#78]
Currently the data are plotted with a data regular scale. So 1 data point = 1 increment. But we were tracking by day at the beginning and per hour after this. It's why it seems there is an artificial drop at the beginning.

<img width="962" alt="capture d ecran 2018-06-26 a 17 46 09" src="https://user-images.githubusercontent.com/505230/41900143-f84f9ab0-7968-11e8-839b-316eb2c2b962.png">

the scale should be per hour. :)

**Comment by karlcow** [comment]
Here a link.
https://webcompat.github.io/webcompat-metrics-client/?from=2018-01-01&to=2018-08-31

@magsout Currently the data are on 1 data point = 1 linear unit.
But this is not the reality of data.  It's why the X axis looks weird. 
The X axis should be done with a time axis.

if the library you are using doesn't know about time. There's a way for you to handle this.
The timestamp has currently this format.

`2018-08-22T05:59:59Z`

```js
var isodate = "2018-08-22T05:59:59Z";
// returns milliseconds so divide by 1000 to have seconds.
var ts = (new Date(isodate)).getTime()/1000; 
ts
1534917599
```

so you can plot a value on a linear axis in seconds and link the point from this.

**Comment by magsout** [comment]
@karlcow sorry, I don't get it.

Why do you say that the X axis looks weird? I don't understand why the X axis should be done with a time axis? Why the type of X axis matters?

If I consider the X axis without transform it I get :

![capture d ecran 2018-08-23 a 07 57 37](https://user-images.githubusercontent.com/1997108/44507639-8cffe880-a6ab-11e8-93fb-8e1037dd8bc6.png)

It seems the library I'm using doesn't car about types of value. It takes two point, a X and a Y then draw a point and draw a line between point that's it, oh and reduce the numbers of X writing then, improving the display.

**Comment by magsout** [comment]
But `It seems the library I'm using doesn't car about types of value. ` maybe that's the problem, so it's why I don't see the value

**Comment by karlcow** [comment]
Ah… 
https://github.com/webcompat/webcompat-metrics-client/blob/0cae4157b9079161794b172cd32780f7afd61411/src/modules/needsDiagnosis/index.js#L109

@magsout the code seems to normalize data into days. instead of YYYY-MM-DD HH:MM:SS So it's probably why we get straight vertical line when we switch the distribution to `linear`.

So summary

* distribution: linear
* parsing the full date for normalization not just the day.

**Comment by magsout** [comment]
@karlcow I sent into the component the Date directly. 

![capture d ecran 2018-08-24 a 08 41 20](https://user-images.githubusercontent.com/1997108/44569109-9bb4d100-a779-11e8-9548-a528c595f3f3.png)

what do you think ?

**Comment by magsout** [comment]
data : `dayjs(new Date(stat.timestamp)).format("YYYY-MM-DD hh:mm:ss"),` type string
options: `{scales: {xAxes: [{type: "time",distribution: "linear",},], },}`

![capture d ecran 2018-08-24 a 08 48 40](https://user-images.githubusercontent.com/1997108/44569403-868c7200-a77a-11e8-9953-9a7053e7e11e.png)

**Comment by karlcow** [comment]
super! @magsout 
I think we could drop the round dot and just draw the line. `pointRadius: 0`

**Comment by magsout** [comment]
with `pointRadius: 0`:

![capture d ecran 2018-08-24 a 14 08 21](https://user-images.githubusercontent.com/1997108/44583821-37106b00-a7a7-11e8-805d-f3ed6ca6dc23.png)

**Comment by magsout** [comment]
I'm trying looking for why I get this and I'll commit then.
![capture d ecran 2018-08-24 a 14 11 44](https://user-images.githubusercontent.com/1997108/44583965-a5edc400-a7a7-11e8-93b1-6d117349884c.png)
