### ISSUE TITLE
Add Triage Dashboard

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat-metrics-client#85]
Can we extend the NeedsDiagnosis Graph Dashboard to Triage as well?
I think it would be interesting to see the pattern of the Triage activity, and maybe learn something from this.

https://webcompat.github.io/webcompat-metrics-client/?from=2018-05-01&to=2018-07-12

Maybe something like this?
![image](https://user-images.githubusercontent.com/16573771/42925747-d3bcd344-8b37-11e8-9c23-89b1c7de62b0.png)

**Comment by laghee** [comment]
Edited the title to mirror the other pending requests for dashboards: weekly report and outreach. Dashboarding ftw! 📊 🔮 🚀
